In [1]:
import numpy as np 
import pandas as pd

In [2]:
cars_train=pd.read_csv(r"C:\Users\91987\Downloads\cars_train.csv",header=None)
cars_test=pd.read_csv(r"C:\Users\91987\Downloads\cars_test.csv",header=None)

In [3]:
cars_train.shape

(1382, 7)

In [4]:
cars_test.shape

(346, 7)

In [5]:
cars_train.head()

0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [6]:
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [7]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [8]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [9]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [10]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [11]:
cars_test.drop('classes',axis=1,inplace=True)
cars_test.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [12]:
colname=cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [13]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [14]:
cars_train.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [15]:
colname1=cars_test.columns
colname1

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [16]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname1:
    cars_test[x]=le.fit_transform(cars_test[x])

In [17]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [18]:
X=cars_train.values[:,0:-1]
Y=cars_train.values[:,-1]
Y=Y.astype(int)

In [19]:
X.shape

(1382, 6)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [21]:
X

array([[ 1.33507272, -1.3488262 , -0.45682233,  1.21505861,  1.22565305,
         0.00176987],
       [-0.44760409,  1.32688358, -0.45682233, -0.01064285,  1.22565305,
         1.22474807],
       [-0.44760409, -1.3488262 ,  1.33418038,  1.21505861, -1.21505663,
         0.00176987],
       ...,
       [-1.33894249,  1.32688358,  1.33418038, -0.01064285,  0.00529821,
        -1.22120833],
       [ 0.44373431,  0.43498032,  0.43867903, -0.01064285, -1.21505663,
         0.00176987],
       [ 0.44373431, -0.45692294,  1.33418038,  1.21505861,  1.22565305,
        -1.22120833]])

In [22]:
from sklearn.model_selection import train_test_split
# Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [23]:
# Running Decision Tree Model

In [24]:
# predicting using the Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10,splitter='best',min_samples_leaf=2,
                                         min_samples_split=5,max_depth=10)

# fit the model on the data and predict the values 
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 65   2   4   0]
 [  3   7   0   2]
 [  2   0 183   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.78      0.58      0.67        12
           2       0.98      0.99      0.98       185
           3       0.82      1.00      0.90         9

    accuracy                           0.95       277
   macro avg       0.88      0.87      0.87       277
weighted avg       0.95      0.95      0.95       277

Accuracy of the model:  0.9530685920577617


In [26]:
model_DecisionTree.score(X_train,Y_train)

0.9809954751131221

In [27]:
print((list(zip(cars_train.columns[0:-1],
               model_DecisionTree.feature_importances_))))

[('buying', 0.22691941670455307), ('maint', 0.19278285017423907), ('doors', 0.05766854734910144), ('persons', 0.17112178616390536), ('lug_boot', 0.09331548954995343), ('safety', 0.25819191005824765)]


In [28]:
# if the values is very very less than eliminate those variables
# we can further more eliminate some more variables which show negligible importance


In [29]:
sample=pd.DataFrame()
 
sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

Column  Imp value
5    safety   0.258192
0    buying   0.226919
1     maint   0.192783
3   persons   0.171122
4  lug_boot   0.093315
2     doors   0.057669

In [30]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
 
# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=90,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [32]:
# now, create a list with the objects 
models= [tree, knn, svm, logreg]

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
 
for model in models:
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  97.83393501805054
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



[[ 66   0   5   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   1   6]]
The accuracy of the  KNeighborsClassifier  model is  93.86281588447653
Classification report:
               precision    recall  f1-score   support

           0       0.86      0.93      0.89        71
           1       1.00      0.33      0.50        12
           2       0.97      0.99      0.98       185


C:\Users\91987\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
# 1-- Building multiple individual models--select the best one
# 2-- Building the combination of models---aggregating the output i.e ensembling the model

In [35]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [36]:
test=cars_test.values
test=scaler.transform(test)
#print(test)

In [37]:
# predicting using the Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10,splitter='best')

# fit the model on the data and predict the values 
model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=10, splitter='best')

In [38]:
test_pred=model_DecisionTree.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [39]:
cars_test=pd.read_csv(r"C:\Users\91987\Downloads\cars_test.csv",header=None)
cars_test.columns=['buying','maint','doors','persons',
                   'lug_boot','safety','classes']
cars_test["Pred"]=test_pred
cars_test["Pred"]=cars_test["Pred"].map({0:"acc",1:"good",2:"unacc",
                                         3:"vgood"})
cars_test.head()

buying  maint  doors persons lug_boot safety classes   Pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# confusion matrix
print(confusion_matrix(cars_test.classes,cars_test.Pred))
print(accuracy_score(cars_test.classes,cars_test.Pred))
print(classification_report(cars_test.classes,cars_test.Pred))


# we can see accuracy matches validation data 

[[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
0.9797687861271677
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346



In [41]:
cars_test.to_excel("Decision Test Output.xlsx",header=True)

# predicting using the random_forest_classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=200,random_state=10,
                                         bootstrap=True,max_features=0.6)
# fit the model on the data and predict the values 
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   0   2   0]
 [  3   8   0   1]
 [  1   0 184   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       1.00      0.67      0.80        12
           2       0.99      0.99      0.99       185
           3       0.90      1.00      0.95         9

    accuracy                           0.97       277
   macro avg       0.96      0.91      0.92       277
weighted avg       0.98      0.97      0.97       277

Accuracy of the model:  0.9747292418772563


In [44]:
from sklearn.ensemble import ExtraTreesClassifier

model_EXT=ExtraTreesClassifier(n_estimators=200,random_state=10, bootstrap=True)
# fit the model on the data and predict the values 
model_EXT.fit(X_train,Y_train)

Y_pred=model_EXT.predict(X_test)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 63   0   8   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   0   7]]
Classification report: 
              precision    recall  f1-score   support

           0       0.85      0.89      0.87        71
           1       1.00      0.33      0.50        12
           2       0.96      0.99      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.93       277
   macro avg       0.95      0.75      0.81       277
weighted avg       0.93      0.93      0.92       277

Accuracy of the model:  0.9314079422382672


# Running Adaboost Classifier

In [46]:
# predicting using Adaboost_Classifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=
                                 DecisionTreeClassifier(random_state=10),
                                 n_estimators=100,
                                 random_state=10)
# fit the model on the data and predict the values 
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)


In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model:  0.9783393501805054


# Running Gradient Boosting Classifier

In [48]:
# predicting using Adaboost_Classifier
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier(n_estimators=300,random_state=10)
# fit the model on the data and predict the values 
model_GradientBoosting.fit(X_train,Y_train)
Y_pred=model_GradientBoosting.predict(X_test)


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 71   0   0   0]
 [  1  11   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        71
           1       1.00      0.92      0.96        12
           2       1.00      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           1.00       277
   macro avg       1.00      0.98      0.99       277
weighted avg       1.00      1.00      1.00       277

Accuracy of the model:  0.9963898916967509


In [50]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


# Running XGBoost

In [51]:
from xgboost import XGBClassifier
model_GradientBoosting=XGBClassifier(n_estimatores=100,random_state=10)

# fit the model on the data and predict the values 
model_GradientBoosting.fit(X_train,Y_train)
Y_pred=model_GradientBoosting.predict(X_test)


[10:41:39] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/learner.cc:627: 
Parameters: { "n_estimatores" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   1   1   0]
 [  3   9   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.96      0.97      0.97        71
           1       0.90      0.75      0.82        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.93      0.95       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model:  0.9819494584837545


# Ensemble Modelling (Voting Classifier)

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
 

In [54]:
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
estimators.append(('svm', model3))
#model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
#estimators.append(('knn', model4))

In [55]:
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 70   0   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.95      0.99      0.97        71
           1       1.00      0.67      0.80        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.99      0.91      0.94       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model:  0.9819494584837545


# stacking classifier

In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [72]:
# create the sub models
level0 = []
model1 = LogisticRegression()
level0.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
level0.append(('cart', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
level0.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
level0.append(('knn', model4))

In [73]:
level1=LogisticRegression()
 
# create the ensemble model
ensemble = StackingClassifier(estimators=level0, final_estimator=level1, cv=5,passthrough=False)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)
# passthrough =false means that meta classifier will be trained only on the output recieved from the beta classifier
# if pass trough=True it menas that meta classifier will be trained only on the output recieved from the beta classifier
#and also on the orignal training data

C:\Users\91987\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
Classification report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277

Accuracy of the model:  0.9855595667870036
